### ISSUE TITLE
UI/UX issues with the interactive "Global Emissions" chart

### ISSUE THREAD

**Issue by ChaoticNeutralCzech** [klimadashboard/data#1]
- North Korea and South Korea have the same country code so they're broken
- Some country names in English rather than German - *France*, *European Union*, *Russia* (*Côte d’Ivoire* is the correct country name but it does not work.)
- Adding a country is not intuitive. Maybe use "+" as the default text in the search box, cleared when clicked?
- Selecting a country from the search results does not reset the search query
- The chart has an element ID `globalemissions` but you cannot link to it using https://klimadashboard.de/emissionen#globalemissions - would be useful on such a long page, along with a Permalink [🔗] button next to the Embed one
- You cannot share your country selection using URL parameters (it would be cool if the browser URL (as well as the Permalink [🔗] button URL) changed to https://klimadashboard.de/emissionen?land=CN+DE+SE+US when you remove Italy, for example)

**Comment by davidjablonski** [comment]
Thank you for raising this detailed issue. We’re working on a way to include selected parameters in the browser URL, this is unfortunately more challenging as we’d like to make this available across all our charts in a standardised way. We’ll open a separate issue and track progress there. The remaining issues pertaining to the global emissions chart were resolved as best as possible with the latest update.
