### ISSUE TITLE
Noch weniger Zeit für 1,5-Grad-Klimaziel?

### ISSUE THREAD

**Issue by feinstaub** [klimadashboard/data#2]
Hi, super nützliches Dashboard. Danke dafür!

Ist das hier mit berücksichtigt bzw. wie ändern sich die Charts, wenn man es tut? https://www.tagesschau.de/wissen/klima/erderwaermung-100.html

Danke!

**Comment by pweigmann** [comment]
Die Daten auf unserer Website basieren momentan auf der 2022 aktualisierten Berechnung des IPCC im AR6, welche ein globales Budget von 500 GtCO2 für 50%iges Erreichen von 1.5°C annehmen. Diese 500 GtCO2 zählen ab Anfang 2020. Die von dir verlinkte Studie schätzt das Budget mit ca. 250 GtCO2 ab Anfang 2023 ab und gibt damit die ernstzunehmende Sorge auf, dass wir bisher das verbleibende Budget überschätzen.

Es ist bisher jedoch (noch) eine einzelne Studie und kein systematisches Review, wie es vom IPCC vorgenommen wurde, daher kann ich gerade noch nicht bestätigen, dass wir die Zahlen auf der Website ändern werden. 

Allerdings haben wir unser Budget schon in der Hinsicht angepasst, dass wir die Emissionen bis Anfang 2023 vom verbleibenden Budget abgezogen haben - für das erwähnte 1.5°C Budget heißt das, dass wir in den Grafiken ein Budget von ca. 380 GtCO2 ab 2023 darstellen, welches der aktuellen Studie zumindest etwas näher kommt indem es die Emissionen der letzten drei Jahre miteinbezieht.
